### ISSUE TITLE
globalepistasis_fits

### ISSUE THREAD

**Issue by yamin-19** [dms-vep/flu_h3_hk19_dms#51]
I am very passionate about the "globalepistasis_fits" calculation, but unfortunately, due to the missing data of “results/func_scores/functional_selections.csv”, it's regrettable that this calculation cannot be performed.
Can I kindly ask you to share and upload the relevant data when convenient?

**Comment by jbloom** [comment]
@yamin-19, we are happy to add these data to GitHub tracking, but can you be more clear which data you need?

We do have the variant counts (which are the input to the global epistasis fitting I think?) tracked in files like these: https://github.com/dms-vep/flu_h3_hk19_dms/blob/main/results/variant_counts/libA_221223_1_no-antibody_control_1.csv

Are there other or specific files you need added to the GitHub repo? If so, just specify what they are and we will add them.

**Comment by yamin-19** [comment]
I truly appreciate the time and effort you have invested in providing me with access to these datasets, and I am deeply grateful for your support. 
I would like to reproduce the computational process you shared: https://dms-vep.org/flu_h3_hk19_dms/fit_globalepistasis.html
I need the data from these files in the directory:
flu_h3_hk19_dms/results/func_scores/functional_selections.csv
It's just these:
libA_220303_1_plasmid_1_vs_221027_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230221_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230317_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230323_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230403_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230419_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230425_1_no-antibody_control_1
libA_220303_1_plasmid_1_vs_230620_1_no-antibody_control_1
libB_220303_1_plasmid_1_vs_230118_1_no-antibody_control_1
libB_220303_1_plasmid_1_vs_230407_1_no-antibody_control_1
libB_220303_1_plasmid_1_vs_230412_1_no-antibody_control_1
libB_220303_1_plasmid_1_vs_230502_1_no-antibody_control_1

**Comment by jbloom** [comment]
@fwelsh, can you address this issue? All you need to do is as follows:

1. Go to the latest version of your repo on the server that contains all the results from running the pipeline.
2. Add the following line to the `.gitignore`: `!results/func_scores/*_func_scores.csv`  (that will start tracking the file in question)
3. `git` add and commit the changes to the `.gitignore` and the new CSV files that should now be tracked.
4. Make a pull request.

That should provide the files in the repo for @yamin-19

**Comment by yamin-19** [comment]
I deeply appreciate your support and guidance！

**Comment by fwelsh** [comment]
@yamin-19 apologies for the delay on this, but the files in [results/func_scores/](https://github.com/dms-vep/flu_h3_hk19_dms/tree/main/results/func_scores) should now be available! Please let us know if any other issues come up.
